### ISSUE TITLE
Make on macOS failes

### ISSUE THREAD

**Issue by razaba** [MustaphaTR/Generals-Alpha#1]
when I try to run make on my mac I get this error:
Raz-MACLP:Generals-Alpha raz$ make
/bin/sh: ./fetch-engine.sh: Permission denied
Unable to continue without engine files
make: *** [engine] Error 1
Raz-MACLP:Generals-Alpha raz$ chmod 777 . -R
Raz-MACLP:Generals-Alpha raz$ make
OpenRA engine version gen-20170925 is required.
Downloading engine...
Compiling engine...
Fetching StyleCopPlus from NuGet
Fetching StyleCop files from NuGet
Fetching ICSharpCode.SharpZipLib from NuGet
Fetching MaxMind.Db from NuGet
Fetching SharpFont from NuGet
Fetching NUnit from NuGet
Fetching NUnit.Console from NuGet
Fetching Open.Nat from NuGet
mv: cannot move 'Open.NAT' to a subdirectory of itself, 'Open.Nat/Open.NAT'
make[1]: *** [cli-dependencies] Error 1
make: *** [engine] Error 2

can you assist?

**Comment by MustaphaTR** [comment]
Can you try again? I updated the files as @pchote said on IRC. It should be working now.

**Comment by razaba** [comment]
no, sorry. still not working.
Fetching Open.Nat from NuGet
mv: cannot move 'Open.NAT' to a subdirectory of itself, 'Open.Nat/Open.NAT'
make[1]: *** [cli-dependencies] Error 1
make: *** [engine] Error 2

**Comment by MustaphaTR** [comment]
You have redownloaded it from here, right? Not just retried to do make on existing one?

If you did first, i'm not sure what else can be problem, i'm not a Mac user. If you did the latter, delete the old download and try a new one on a clean installation.

**Comment by pchote** [comment]
@MustaphaTR: It looks like you didn't push the updated files to github.  All the launch scripts on https://github.com/MustaphaTR/Generals-Alpha are showing as last modified 17 days ago.

**Comment by MustaphaTR** [comment]
@razaba Can you try once more, i think i fixed it this time.

**Comment by pchote** [comment]
While not specifically related to this issue, it looks like you've updated to a newish bleed but have not updated the `PACKAGING_OSX_LAUNCHER_TAG` in your mod.config to match.  That should now be `osx-launcher-20171118`.

**Comment by MustaphaTR** [comment]
Condiering the travis error SoScrared was getting, and i'm not getting that error. This should be fixed.
